name: CI

on: [push, pull_request]

jobs:
  Apple:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test building for iOS
        run: xcodebuild -scheme SwiftYogaKit -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'
      - name: Test building for tvOS
        run: xcodebuild -scheme SwiftYogaKit -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV'
      - name: Test building for macOS (x86_64 & arm64)
        run: xcodebuild -scheme SwiftYogaKit -sdk macosx -arch x86_64 -arch arm64
